name: p

on:
  schedule:
    - cron: '*/1 * * * *' # Menjalankan workflow setiap menit
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual

jobs:
  fetch-and-combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Versi Node.js yang sesuai

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Create and run fetch and combine script
        run: |
          # Buat file script proxy.js
          echo "const fs = require('fs');
          const fetch = require('node-fetch');

          const fileUrls = [
              'https://github.com/ErcinDedeoglu/proxies/raw/refs/heads/main/proxies/http.txt',
              'https://github.com/ErcinDedeoglu/proxies/raw/refs/heads/main/proxies/https.txt',
              'https://github.com/ErcinDedeoglu/proxies/raw/refs/heads/main/proxies/socks4.txt',
              'https://github.com/ErcinDedeoglu/proxies/raw/refs/heads/main/proxies/socks5.txt',
              'https://github.com/hookzof/socks5_list/raw/refs/heads/master/proxy.txt',
              'https://github.com/MyZest/update-live-socks5/raw/refs/heads/master/liveSocks5.txt',
              'https://github.com/r00tee/Proxy-List/raw/refs/heads/main/Socks5.txt',
              'https://github.com/r00tee/Proxy-List/raw/refs/heads/main/Socks4.txt',
              'https://github.com/r00tee/Proxy-List/raw/refs/heads/main/Https.txt',
              'https://github.com/babyhagey74/free-proxies/raw/refs/heads/main/proxies/http/http.txt',
              'https://github.com/babyhagey74/free-proxies/raw/refs/heads/main/proxies/https/https.txt',
              'https://github.com/babyhagey74/free-proxies/raw/refs/heads/main/proxies/socks4/socks4.txt',
              'https://github.com/babyhagey74/free-proxies/raw/refs/heads/main/proxies/socks5/socks5.txt',
              'https://github.com/Vann-Dev/proxy-list/raw/refs/heads/main/proxies/http.txt',
              'https://github.com/Vann-Dev/proxy-list/raw/refs/heads/main/proxies/https.txt',
              'https://github.com/Vann-Dev/proxy-list/raw/refs/heads/main/proxies/socks4.txt',
              'https://github.com/Vann-Dev/proxy-list/raw/refs/heads/main/proxies/socks5.txt',
              'https://github.com/zloi-user/hideip.me/raw/refs/heads/main/http.txt',
              'https://github.com/zloi-user/hideip.me/raw/refs/heads/main/https.txt',
              'https://github.com/zloi-user/hideip.me/raw/refs/heads/main/socks4.txt',
              'https://github.com/zloi-user/hideip.me/raw/refs/heads/main/socks5.txt',
              'https://github.com/ALIILAPRO/Proxy/raw/refs/heads/main/http.txt',
              'https://github.com/ALIILAPRO/Proxy/raw/refs/heads/main/socks4.txt',
              'https://github.com/ALIILAPRO/Proxy/raw/refs/heads/main/socks5.txt',
              'https://github.com/sunny9577/proxy-scraper/raw/refs/heads/master/generated/http_proxies.txt',
              'https://github.com/sunny9577/proxy-scraper/raw/refs/heads/master/generated/socks4_proxies.txt',
              'https://github.com/sunny9577/proxy-scraper/raw/refs/heads/master/generated/socks5_proxies.txt',
              
          ];

          async function fetchFileContent(url) {
              try {
                  const response = await fetch(url);
                  if (!response.ok) throw new Error(\`Gagal mengambil file: \${url}\`);
                  return await response.text();
              } catch (error) {
                  console.error(error);
                  return '';
              }
          }

          async function combineFiles() {
              let combinedContent = '';
              for (const url of fileUrls) {
                  const content = await fetchFileContent(url);
                  combinedContent += content + '\\n\\n';
              }
              fs.writeFileSync('active_proxies.txt', combinedContent);
              console.log('File berhasil digabungkan ke active_proxies.txt');
          }

          combineFiles();" > proxy.js
          
          # Jalankan script
          node proxy.js

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "${{ secrets.EMAIL }}"
          git add active_proxies.txt || echo "active_proxies.txt tidak ada"
          git commit -m "Update active proxies" || echo "Tidak ada perubahan untuk di-commit"
          git pull --rebase origin main || echo "Tidak ada perubahan dari remote untuk di-pull"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
